#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

case "$1" in
  help | post-deploy-script:help)
    help_content_func() {
      #shellcheck disable=SC2034
      declare desc="return help_content string"

      cat<<help_content
    post-deploy-script:show <app>, Shows the content of the POST_DEPLOY_SCRIPT
    post-deploy-script:report <app>, Display the configuration for an app
    post-deploy-script:disable <app>, disables the execution of the post deploy script for an app
    post-deploy-script:enable <app>, (re)enables the execution of the post deploy script for an app (if present)
help_content
    }

    if [[ $1 = "post-deploy-script:help" ]]; then
      echo -e 'Usage: dokku post-deploy-script[:COMMAND] [<app>]'
      echo ''
      echo -e 'Commands:'
      help_content_func | sort | column -c2 -t -s,
    else
      cat<<help_desc
    post-deploy-script, Plugin to run scripts on the dokku host after deploy (not within the apps container)
help_desc
    fi
    ;;

  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;

esac