#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

post_deploy_script_show_cmd() {
  #shellcheck disable=SC2034
  declare desc="Show the content of the POST_DEPLOY_SCRIPT"
  local cmd="post-deploy-script:show"
  # Support --app/$DOKKU_APP_NAME flag
  # Use the following lines to reorder args into "$cmd $DOKKU_APP_NAME $@""
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  APP="$2"
  [[ -z "$APP" ]] && dokku_log_fail "Please specify an app to run the command on"
  verify_app_name "$APP"

  if [[ ! -d "$DOKKU_ROOT/$APP/post-deploy-scripts" || ! -f "$DOKKU_ROOT/$APP/post-deploy-scripts/POST_DEPLOY_SCRIPT" ]]; then
        dokku_log_warn "No post deploy script (POST_DEPLOY_SCRIPT) found in the app's container: $APP"
  else
        dokku_log_info1 "POST_DEPLOY_SCRIPT"
        dokku_log_info1 "$(cat $DOKKU_ROOT/$APP/post-deploy-scripts/POST_DEPLOY_SCRIPT)"
  fi
}

post_deploy_script_show_cmd "$@"